name: Robot Scraper WTTJ

on:
  schedule:
    # Tourne tous les jours à 08h00 (Heure UTC)
    - cron: '0 8 * * *'
  workflow_dispatch:

# --- LE CORRECTIF GITHUB EST ICI ---
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  extraction-data:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Récupérer le code sur le dépôt
      uses: actions/checkout@v4

    - name: 2. Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 3. Installer les bibliothèques
      run: pip install -r requirements.txt

    - name: 4. Lancer l'extraction vers Supabase
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python main.py